add_subdirectory(WIZnet_ArduCAMMega_UDP_Streaming)
add_subdirectory(WIZnet_ArduCAMMega_TOE_Web_Streaming)
add_subdirectory(WIZnet_ArduCAMMega_Lwip_Web_Streaming)
add_subdirectory(WIZnet_ArduCAMMega_Exhibition)
add_subdirectory(WIZnet_ArduCAMMega_TCPWeb_Streaming)
add_subdirectory(WIZnet_I2S_Mic_Test)
add_subdirectory(WIZnet_Discord_Test)
add_subdirectory(WIZnet_WaterTank)
add_subdirectory(watertank_LH_20261007)
add_subdirectory(WIZnet_OV2640_Exhibition)
