/**
 * @file    web_page.h
 * @brief   Embedded single-page UI for the ArduCAM MEGA TCP web streaming example.
 *
 * The whole UI is one self-contained string: no external CSS, JS, fonts, or images,
 * because the device is the only server the browser can reach.
 *
 * Brand colours live in the :root block below. Change those variables to restyle
 * the page; nothing else hard-codes a colour.
 *
 * HTML attributes use single quotes so the C string needs no escaping.
 */

#ifndef WEB_PAGE_H
#define WEB_PAGE_H

static const char HTTP_INDEX_PAGE[] =
"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>WIZnet Camera Stream</title>\n"
"<style>\n"
":root{\n"
"  --bg:#0d1520; --panel:#152233; --line:#22344b;\n"
"  --text:#e8eef6; --muted:#8fa3ba;\n"
"  --accent:#00b8d4; --ok:#3ddc84; --stop:#ff5c5c;\n"
"}\n"
"*{box-sizing:border-box}\n"
"body{margin:0;background:var(--bg);color:var(--text);\n"
"  font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif}\n"
"header{display:flex;align-items:center;gap:12px;padding:14px 20px;\n"
"  background:var(--panel);border-bottom:2px solid var(--accent)}\n"
"header .logo{font-weight:700;font-size:20px;letter-spacing:.5px}\n"
"header .logo span{color:var(--accent)}\n"
"header .sub{color:var(--muted);font-size:13px}\n"
"main{max-width:1100px;margin:0 auto;padding:20px;\n"
"  display:grid;grid-template-columns:minmax(0,2fr) minmax(240px,1fr);gap:20px}\n"
"@media(max-width:820px){main{grid-template-columns:1fr}}\n"
".card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px}\n"
".card h2{margin:0 0 12px;font-size:14px;text-transform:uppercase;\n"
"  letter-spacing:1px;color:var(--muted);font-weight:600}\n"
".view{background:#000;border-radius:8px;overflow:hidden;\n"
"  display:flex;align-items:center;justify-content:center;min-height:240px}\n"
".view img{width:100%;height:auto;display:block}\n"
".btns{display:flex;gap:10px;margin-bottom:16px}\n"
"button{flex:1;padding:12px;border:0;border-radius:8px;cursor:pointer;\n"
"  font-size:15px;font-weight:600;color:#08121c;transition:opacity .15s}\n"
"button:hover{opacity:.85}\n"
"button:disabled{opacity:.35;cursor:not-allowed}\n"
"#start{background:var(--ok)}\n"
"#stop{background:var(--stop)}\n"
"select{width:100%;padding:10px;border-radius:8px;border:1px solid var(--line);\n"
"  background:var(--bg);color:var(--text);font-size:14px}\n"
"label{display:block;font-size:12px;color:var(--muted);margin:0 0 6px}\n"
"dl{display:grid;grid-template-columns:auto 1fr;gap:8px 12px;margin:16px 0 0;font-size:14px}\n"
"dt{color:var(--muted)}\n"
"dd{margin:0;text-align:right;font-variant-numeric:tabular-nums}\n"
".dot{display:inline-block;width:8px;height:8px;border-radius:50%;\n"
"  margin-right:7px;background:var(--muted);vertical-align:middle}\n"
".dot.live{background:var(--ok);box-shadow:0 0 8px var(--ok)}\n"
"footer{text-align:center;color:var(--muted);font-size:12px;padding:8px 0 24px}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div class='logo'>WIZ<span>net</span></div>\n"
"  <div class='sub'>ArduCAM MEGA &middot; TCP Web Streaming</div>\n"
"</header>\n"
"<main>\n"
"  <section class='card'>\n"
"    <h2><span id='dot' class='dot'></span>Live view</h2>\n"
"    <div class='view'><img id='view' src='/stream' alt='camera stream'></div>\n"
"  </section>\n"
"  <section class='card'>\n"
"    <h2>Control</h2>\n"
"    <div class='btns'>\n"
"      <button id='start'>START</button>\n"
"      <button id='stop'>STOP</button>\n"
"    </div>\n"
"    <label for='res'>Resolution</label>\n"
"    <select id='res'>\n"
"      <option value='320x240'>320 x 240</option>\n"
"      <option value='640x480'>640 x 480</option>\n"
"      <option value='1280x720'>1280 x 720</option>\n"
"      <option value='1600x1200'>1600 x 1200</option>\n"
"      <option value='1920x1080'>1920 x 1080</option>\n"
"    </select>\n"
"    <dl>\n"
"      <dt>State</dt><dd id='s-state'>-</dd>\n"
"      <dt>Resolution</dt><dd id='s-res'>-</dd>\n"
"      <dt>Frames</dt><dd id='s-frames'>-</dd>\n"
"      <dt>Dropped</dt><dd id='s-drop'>-</dd>\n"
"    </dl>\n"
"  </section>\n"
"</main>\n"
"<footer>WIZnet hardwired TCP/IP &middot; served from the device</footer>\n"
"<script>\n"
"var $=function(id){return document.getElementById(id)};\n"
"function call(p){return fetch(p).then(function(r){return r.json()}).then(render)}\n"
"function render(s){\n"
"  $('s-state').textContent=s.streaming?'STREAMING':'STOPPED';\n"
"  $('s-res').textContent=s.res;\n"
"  $('s-frames').textContent=s.frames;\n"
"  $('s-drop').textContent=s.dropped;\n"
"  $('dot').className='dot'+(s.streaming?' live':'');\n"
"  $('start').disabled=s.streaming;\n"
"  $('stop').disabled=!s.streaming;\n"
"  if($('res').value!==s.res){$('res').value=s.res}\n"
"}\n"
"$('start').onclick=function(){call('/api/start')};\n"
"$('stop').onclick=function(){call('/api/stop')};\n"
"$('res').onchange=function(){call('/api/res?v='+this.value)};\n"
"setInterval(function(){call('/api/status').catch(function(){})},1000);\n"
"call('/api/status').catch(function(){});\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* WEB_PAGE_H */
